services:
  db:
    restart: on-failure
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    restart: on-failure
    image: redis:latest
    ports:
      - "6379:6379"

  web-service:
    restart: on-failure
    build: ./
    ports:
      - "8080:8080"
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=${POSTGRES_USER}
    - DB_PASS=${POSTGRES_PASSWORD}
    - DB_NAME=${POSTGRES_DB}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=
    - REDIS_DB=0
    depends_on:
      - db
      - redis

volumes:
  pgdata:
